// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/examples/lettercount/lettercount.proto

package lettercount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InputString is a leaf input proto containing the string to analyze
type InputString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputString) Reset() {
	*x = InputString{}
	mi := &file_proto_examples_lettercount_lettercount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputString) ProtoMessage() {}

func (x *InputString) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_lettercount_lettercount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputString.ProtoReflect.Descriptor instead.
func (*InputString) Descriptor() ([]byte, []int) {
	return file_proto_examples_lettercount_lettercount_proto_rawDescGZIP(), []int{0}
}

func (x *InputString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// LetterCount is the output proto containing the count of letter 'r'
type LetterCount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalString string                 `protobuf:"bytes,1,opt,name=original_string,json=originalString,proto3" json:"original_string,omitempty"`
	TargetLetter   string                 `protobuf:"bytes,2,opt,name=target_letter,json=targetLetter,proto3" json:"target_letter,omitempty"`
	Count          int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LetterCount) Reset() {
	*x = LetterCount{}
	mi := &file_proto_examples_lettercount_lettercount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LetterCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LetterCount) ProtoMessage() {}

func (x *LetterCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_lettercount_lettercount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LetterCount.ProtoReflect.Descriptor instead.
func (*LetterCount) Descriptor() ([]byte, []int) {
	return file_proto_examples_lettercount_lettercount_proto_rawDescGZIP(), []int{1}
}

func (x *LetterCount) GetOriginalString() string {
	if x != nil {
		return x.OriginalString
	}
	return ""
}

func (x *LetterCount) GetTargetLetter() string {
	if x != nil {
		return x.TargetLetter
	}
	return ""
}

func (x *LetterCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_examples_lettercount_lettercount_proto protoreflect.FileDescriptor

const file_proto_examples_lettercount_lettercount_proto_rawDesc = "" +
	"\n" +
	",proto/examples/lettercount/lettercount.proto\x12\x1bdocket.examples.lettercount\"#\n" +
	"\vInputString\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"q\n" +
	"\vLetterCount\x12'\n" +
	"\x0foriginal_string\x18\x01 \x01(\tR\x0eoriginalString\x12#\n" +
	"\rtarget_letter\x18\x02 \x01(\tR\ftargetLetter\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05countB#Z!docket/proto/examples/lettercountb\x06proto3"

var (
	file_proto_examples_lettercount_lettercount_proto_rawDescOnce sync.Once
	file_proto_examples_lettercount_lettercount_proto_rawDescData []byte
)

func file_proto_examples_lettercount_lettercount_proto_rawDescGZIP() []byte {
	file_proto_examples_lettercount_lettercount_proto_rawDescOnce.Do(func() {
		file_proto_examples_lettercount_lettercount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_examples_lettercount_lettercount_proto_rawDesc), len(file_proto_examples_lettercount_lettercount_proto_rawDesc)))
	})
	return file_proto_examples_lettercount_lettercount_proto_rawDescData
}

var file_proto_examples_lettercount_lettercount_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_examples_lettercount_lettercount_proto_goTypes = []any{
	(*InputString)(nil), // 0: docket.examples.lettercount.InputString
	(*LetterCount)(nil), // 1: docket.examples.lettercount.LetterCount
}
var file_proto_examples_lettercount_lettercount_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_examples_lettercount_lettercount_proto_init() }
func file_proto_examples_lettercount_lettercount_proto_init() {
	if File_proto_examples_lettercount_lettercount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_examples_lettercount_lettercount_proto_rawDesc), len(file_proto_examples_lettercount_lettercount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_examples_lettercount_lettercount_proto_goTypes,
		DependencyIndexes: file_proto_examples_lettercount_lettercount_proto_depIdxs,
		MessageInfos:      file_proto_examples_lettercount_lettercount_proto_msgTypes,
	}.Build()
	File_proto_examples_lettercount_lettercount_proto = out.File
	file_proto_examples_lettercount_lettercount_proto_goTypes = nil
	file_proto_examples_lettercount_lettercount_proto_depIdxs = nil
}
