// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/examples/parallel/parallel.proto

package parallel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserID is the leaf input - a user to look up
type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_proto_examples_parallel_parallel_proto_rawDescGZIP(), []int{0}
}

func (x *UserID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UserProfile from the user service
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_examples_parallel_parallel_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// UserPreferences from the preferences service
type UserPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Theme         string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_proto_examples_parallel_parallel_proto_rawDescGZIP(), []int{2}
}

func (x *UserPreferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPreferences) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UserPreferences) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// UserActivity from the analytics service
type UserActivity struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginCount         int32                  `protobuf:"varint,2,opt,name=login_count,json=loginCount,proto3" json:"login_count,omitempty"`
	LastLoginTimestamp int64                  `protobuf:"varint,3,opt,name=last_login_timestamp,json=lastLoginTimestamp,proto3" json:"last_login_timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserActivity) Reset() {
	*x = UserActivity{}
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivity) ProtoMessage() {}

func (x *UserActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivity.ProtoReflect.Descriptor instead.
func (*UserActivity) Descriptor() ([]byte, []int) {
	return file_proto_examples_parallel_parallel_proto_rawDescGZIP(), []int{3}
}

func (x *UserActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserActivity) GetLoginCount() int32 {
	if x != nil {
		return x.LoginCount
	}
	return 0
}

func (x *UserActivity) GetLastLoginTimestamp() int64 {
	if x != nil {
		return x.LastLoginTimestamp
	}
	return 0
}

// EnrichedUser combines data from all three services
type EnrichedUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Preferences   *UserPreferences       `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Activity      *UserActivity          `protobuf:"bytes,3,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedUser) Reset() {
	*x = EnrichedUser{}
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedUser) ProtoMessage() {}

func (x *EnrichedUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_parallel_parallel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedUser.ProtoReflect.Descriptor instead.
func (*EnrichedUser) Descriptor() ([]byte, []int) {
	return file_proto_examples_parallel_parallel_proto_rawDescGZIP(), []int{4}
}

func (x *EnrichedUser) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *EnrichedUser) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *EnrichedUser) GetActivity() *UserActivity {
	if x != nil {
		return x.Activity
	}
	return nil
}

var File_proto_examples_parallel_parallel_proto protoreflect.FileDescriptor

const file_proto_examples_parallel_parallel_proto_rawDesc = "" +
	"\n" +
	"&proto/examples/parallel/parallel.proto\x12\x18docket.examples.parallel\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\\\n" +
	"\x0fUserPreferences\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"z\n" +
	"\fUserActivity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vlogin_count\x18\x02 \x01(\x05R\n" +
	"loginCount\x120\n" +
	"\x14last_login_timestamp\x18\x03 \x01(\x03R\x12lastLoginTimestamp\"\xe0\x01\n" +
	"\fEnrichedUser\x12?\n" +
	"\aprofile\x18\x01 \x01(\v2%.docket.examples.parallel.UserProfileR\aprofile\x12K\n" +
	"\vpreferences\x18\x02 \x01(\v2).docket.examples.parallel.UserPreferencesR\vpreferences\x12B\n" +
	"\bactivity\x18\x03 \x01(\v2&.docket.examples.parallel.UserActivityR\bactivityB Z\x1edocket/proto/examples/parallelb\x06proto3"

var (
	file_proto_examples_parallel_parallel_proto_rawDescOnce sync.Once
	file_proto_examples_parallel_parallel_proto_rawDescData []byte
)

func file_proto_examples_parallel_parallel_proto_rawDescGZIP() []byte {
	file_proto_examples_parallel_parallel_proto_rawDescOnce.Do(func() {
		file_proto_examples_parallel_parallel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_examples_parallel_parallel_proto_rawDesc), len(file_proto_examples_parallel_parallel_proto_rawDesc)))
	})
	return file_proto_examples_parallel_parallel_proto_rawDescData
}

var file_proto_examples_parallel_parallel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_examples_parallel_parallel_proto_goTypes = []any{
	(*UserID)(nil),          // 0: docket.examples.parallel.UserID
	(*UserProfile)(nil),     // 1: docket.examples.parallel.UserProfile
	(*UserPreferences)(nil), // 2: docket.examples.parallel.UserPreferences
	(*UserActivity)(nil),    // 3: docket.examples.parallel.UserActivity
	(*EnrichedUser)(nil),    // 4: docket.examples.parallel.EnrichedUser
}
var file_proto_examples_parallel_parallel_proto_depIdxs = []int32{
	1, // 0: docket.examples.parallel.EnrichedUser.profile:type_name -> docket.examples.parallel.UserProfile
	2, // 1: docket.examples.parallel.EnrichedUser.preferences:type_name -> docket.examples.parallel.UserPreferences
	3, // 2: docket.examples.parallel.EnrichedUser.activity:type_name -> docket.examples.parallel.UserActivity
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_examples_parallel_parallel_proto_init() }
func file_proto_examples_parallel_parallel_proto_init() {
	if File_proto_examples_parallel_parallel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_examples_parallel_parallel_proto_rawDesc), len(file_proto_examples_parallel_parallel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_examples_parallel_parallel_proto_goTypes,
		DependencyIndexes: file_proto_examples_parallel_parallel_proto_depIdxs,
		MessageInfos:      file_proto_examples_parallel_parallel_proto_msgTypes,
	}.Build()
	File_proto_examples_parallel_parallel_proto = out.File
	file_proto_examples_parallel_parallel_proto_goTypes = nil
	file_proto_examples_parallel_parallel_proto_depIdxs = nil
}
