// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/persistence.proto

package framework

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PersistenceEntry is the envelope stored in the database/cache.
type PersistenceEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual result of the step.
	// We use Any so we can store the specific output proto.
	Value *anypb.Any `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// If the step failed, this contains the error message.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// When this entry was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When this entry expires.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Arbitrary metadata (tags).
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistenceEntry) Reset() {
	*x = PersistenceEntry{}
	mi := &file_proto_persistence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistenceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistenceEntry) ProtoMessage() {}

func (x *PersistenceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persistence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistenceEntry.ProtoReflect.Descriptor instead.
func (*PersistenceEntry) Descriptor() ([]byte, []int) {
	return file_proto_persistence_proto_rawDescGZIP(), []int{0}
}

func (x *PersistenceEntry) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PersistenceEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PersistenceEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PersistenceEntry) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PersistenceEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_persistence_proto protoreflect.FileDescriptor

const file_proto_persistence_proto_rawDesc = "" +
	"\n" +
	"\x17proto/persistence.proto\x12\x06docket\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xcb\x02\n" +
	"\x10PersistenceEntry\x12*\n" +
	"\x05value\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12B\n" +
	"\bmetadata\x18\x05 \x03(\v2&.docket.PersistenceEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x18Z\x16docket/proto/frameworkb\x06proto3"

var (
	file_proto_persistence_proto_rawDescOnce sync.Once
	file_proto_persistence_proto_rawDescData []byte
)

func file_proto_persistence_proto_rawDescGZIP() []byte {
	file_proto_persistence_proto_rawDescOnce.Do(func() {
		file_proto_persistence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_persistence_proto_rawDesc), len(file_proto_persistence_proto_rawDesc)))
	})
	return file_proto_persistence_proto_rawDescData
}

var file_proto_persistence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_persistence_proto_goTypes = []any{
	(*PersistenceEntry)(nil),      // 0: docket.PersistenceEntry
	nil,                           // 1: docket.PersistenceEntry.MetadataEntry
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_persistence_proto_depIdxs = []int32{
	2, // 0: docket.PersistenceEntry.value:type_name -> google.protobuf.Any
	3, // 1: docket.PersistenceEntry.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: docket.PersistenceEntry.expires_at:type_name -> google.protobuf.Timestamp
	1, // 3: docket.PersistenceEntry.metadata:type_name -> docket.PersistenceEntry.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_persistence_proto_init() }
func file_proto_persistence_proto_init() {
	if File_proto_persistence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_persistence_proto_rawDesc), len(file_proto_persistence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_persistence_proto_goTypes,
		DependencyIndexes: file_proto_persistence_proto_depIdxs,
		MessageInfos:      file_proto_persistence_proto_msgTypes,
	}.Build()
	File_proto_persistence_proto = out.File
	file_proto_persistence_proto_goTypes = nil
	file_proto_persistence_proto_depIdxs = nil
}
