// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v6.33.1
// source: proto/examples/batch/batch.proto

package batch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Movie represents a single movie in the batch
type Movie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year           int32   `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	RuntimeMinutes int32   `protobuf:"varint,4,opt,name=runtime_minutes,json=runtimeMinutes,proto3" json:"runtime_minutes,omitempty"`
	Rating         float64 `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Genre          string  `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
}

func (x *Movie) Reset() {
	*x = Movie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_examples_batch_batch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_batch_batch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_examples_batch_batch_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Movie) GetRuntimeMinutes() int32 {
	if x != nil {
		return x.RuntimeMinutes
	}
	return 0
}

func (x *Movie) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Movie) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

// EnrichedMovie adds computed fields relative to the batch
type EnrichedMovie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Original            *Movie  `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	AboveAverageRating  bool    `protobuf:"varint,2,opt,name=above_average_rating,json=aboveAverageRating,proto3" json:"above_average_rating,omitempty"`    // rating > batch average
	AboveAverageRuntime bool    `protobuf:"varint,3,opt,name=above_average_runtime,json=aboveAverageRuntime,proto3" json:"above_average_runtime,omitempty"` // runtime > batch average
	RatingPercentile    float64 `protobuf:"fixed64,4,opt,name=rating_percentile,json=ratingPercentile,proto3" json:"rating_percentile,omitempty"`           // where this movie ranks (0-100)
}

func (x *EnrichedMovie) Reset() {
	*x = EnrichedMovie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_examples_batch_batch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrichedMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedMovie) ProtoMessage() {}

func (x *EnrichedMovie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_batch_batch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedMovie.ProtoReflect.Descriptor instead.
func (*EnrichedMovie) Descriptor() ([]byte, []int) {
	return file_proto_examples_batch_batch_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichedMovie) GetOriginal() *Movie {
	if x != nil {
		return x.Original
	}
	return nil
}

func (x *EnrichedMovie) GetAboveAverageRating() bool {
	if x != nil {
		return x.AboveAverageRating
	}
	return false
}

func (x *EnrichedMovie) GetAboveAverageRuntime() bool {
	if x != nil {
		return x.AboveAverageRuntime
	}
	return false
}

func (x *EnrichedMovie) GetRatingPercentile() float64 {
	if x != nil {
		return x.RatingPercentile
	}
	return 0
}

// BatchStats contains aggregate statistics computed across all movies (fan-in)
type BatchStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count          int32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	AverageRating  float64 `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	AverageRuntime float64 `protobuf:"fixed64,3,opt,name=average_runtime,json=averageRuntime,proto3" json:"average_runtime,omitempty"`
	MaxRating      float64 `protobuf:"fixed64,4,opt,name=max_rating,json=maxRating,proto3" json:"max_rating,omitempty"`
	MinRating      float64 `protobuf:"fixed64,5,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	TotalRuntime   int32   `protobuf:"varint,6,opt,name=total_runtime,json=totalRuntime,proto3" json:"total_runtime,omitempty"`
}

func (x *BatchStats) Reset() {
	*x = BatchStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_examples_batch_batch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStats) ProtoMessage() {}

func (x *BatchStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_batch_batch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStats.ProtoReflect.Descriptor instead.
func (*BatchStats) Descriptor() ([]byte, []int) {
	return file_proto_examples_batch_batch_proto_rawDescGZIP(), []int{2}
}

func (x *BatchStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BatchStats) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *BatchStats) GetAverageRuntime() float64 {
	if x != nil {
		return x.AverageRuntime
	}
	return 0
}

func (x *BatchStats) GetMaxRating() float64 {
	if x != nil {
		return x.MaxRating
	}
	return 0
}

func (x *BatchStats) GetMinRating() float64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *BatchStats) GetTotalRuntime() int32 {
	if x != nil {
		return x.TotalRuntime
	}
	return 0
}

var File_proto_examples_batch_batch_proto protoreflect.FileDescriptor

var file_proto_examples_batch_batch_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x62, 0x61, 0x74, 0x63, 0x68, 0x22, 0x98, 0x01,
	0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61,
	0x72, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x69, 0x6e,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x72,
	0x69, 0x63, 0x68, 0x65, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2e, 0x62, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x08,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x14, 0x61, 0x62, 0x6f, 0x76,
	0x65, 0x5f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x61, 0x62, 0x6f, 0x76, 0x65, 0x41, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x32, 0x0a, 0x15, 0x61, 0x62,
	0x6f, 0x76, 0x65, 0x5f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x61, 0x62, 0x6f, 0x76, 0x65,
	0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x69, 0x6c, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x0a,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0e, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x23,
	0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_examples_batch_batch_proto_rawDescOnce sync.Once
	file_proto_examples_batch_batch_proto_rawDescData = file_proto_examples_batch_batch_proto_rawDesc
)

func file_proto_examples_batch_batch_proto_rawDescGZIP() []byte {
	file_proto_examples_batch_batch_proto_rawDescOnce.Do(func() {
		file_proto_examples_batch_batch_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_examples_batch_batch_proto_rawDescData)
	})
	return file_proto_examples_batch_batch_proto_rawDescData
}

var file_proto_examples_batch_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_examples_batch_batch_proto_goTypes = []interface{}{
	(*Movie)(nil),         // 0: protograph.examples.batch.Movie
	(*EnrichedMovie)(nil), // 1: protograph.examples.batch.EnrichedMovie
	(*BatchStats)(nil),    // 2: protograph.examples.batch.BatchStats
}
var file_proto_examples_batch_batch_proto_depIdxs = []int32{
	0, // 0: protograph.examples.batch.EnrichedMovie.original:type_name -> protograph.examples.batch.Movie
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_examples_batch_batch_proto_init() }
func file_proto_examples_batch_batch_proto_init() {
	if File_proto_examples_batch_batch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_examples_batch_batch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_examples_batch_batch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrichedMovie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_examples_batch_batch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_examples_batch_batch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_examples_batch_batch_proto_goTypes,
		DependencyIndexes: file_proto_examples_batch_batch_proto_depIdxs,
		MessageInfos:      file_proto_examples_batch_batch_proto_msgTypes,
	}.Build()
	File_proto_examples_batch_batch_proto = out.File
	file_proto_examples_batch_batch_proto_rawDesc = nil
	file_proto_examples_batch_batch_proto_goTypes = nil
	file_proto_examples_batch_batch_proto_depIdxs = nil
}
