// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/examples/batch/batch.proto

package batch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Movie represents a single movie in the batch
type Movie struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year           int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	RuntimeMinutes int32                  `protobuf:"varint,4,opt,name=runtime_minutes,json=runtimeMinutes,proto3" json:"runtime_minutes,omitempty"`
	Rating         float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Genre          string                 `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_proto_examples_batch_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_batch_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_proto_examples_batch_batch_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Movie) GetRuntimeMinutes() int32 {
	if x != nil {
		return x.RuntimeMinutes
	}
	return 0
}

func (x *Movie) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Movie) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

// EnrichedMovie adds computed fields relative to the batch
type EnrichedMovie struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Original            *Movie                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	AboveAverageRating  bool                   `protobuf:"varint,2,opt,name=above_average_rating,json=aboveAverageRating,proto3" json:"above_average_rating,omitempty"`    // rating > batch average
	AboveAverageRuntime bool                   `protobuf:"varint,3,opt,name=above_average_runtime,json=aboveAverageRuntime,proto3" json:"above_average_runtime,omitempty"` // runtime > batch average
	RatingPercentile    float64                `protobuf:"fixed64,4,opt,name=rating_percentile,json=ratingPercentile,proto3" json:"rating_percentile,omitempty"`           // where this movie ranks (0-100)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrichedMovie) Reset() {
	*x = EnrichedMovie{}
	mi := &file_proto_examples_batch_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedMovie) ProtoMessage() {}

func (x *EnrichedMovie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_batch_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedMovie.ProtoReflect.Descriptor instead.
func (*EnrichedMovie) Descriptor() ([]byte, []int) {
	return file_proto_examples_batch_batch_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichedMovie) GetOriginal() *Movie {
	if x != nil {
		return x.Original
	}
	return nil
}

func (x *EnrichedMovie) GetAboveAverageRating() bool {
	if x != nil {
		return x.AboveAverageRating
	}
	return false
}

func (x *EnrichedMovie) GetAboveAverageRuntime() bool {
	if x != nil {
		return x.AboveAverageRuntime
	}
	return false
}

func (x *EnrichedMovie) GetRatingPercentile() float64 {
	if x != nil {
		return x.RatingPercentile
	}
	return 0
}

// BatchStats contains aggregate statistics computed across all movies (fan-in)
type BatchStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Count          int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	AverageRating  float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	AverageRuntime float64                `protobuf:"fixed64,3,opt,name=average_runtime,json=averageRuntime,proto3" json:"average_runtime,omitempty"`
	MaxRating      float64                `protobuf:"fixed64,4,opt,name=max_rating,json=maxRating,proto3" json:"max_rating,omitempty"`
	MinRating      float64                `protobuf:"fixed64,5,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	TotalRuntime   int32                  `protobuf:"varint,6,opt,name=total_runtime,json=totalRuntime,proto3" json:"total_runtime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchStats) Reset() {
	*x = BatchStats{}
	mi := &file_proto_examples_batch_batch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStats) ProtoMessage() {}

func (x *BatchStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_examples_batch_batch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStats.ProtoReflect.Descriptor instead.
func (*BatchStats) Descriptor() ([]byte, []int) {
	return file_proto_examples_batch_batch_proto_rawDescGZIP(), []int{2}
}

func (x *BatchStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BatchStats) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *BatchStats) GetAverageRuntime() float64 {
	if x != nil {
		return x.AverageRuntime
	}
	return 0
}

func (x *BatchStats) GetMaxRating() float64 {
	if x != nil {
		return x.MaxRating
	}
	return 0
}

func (x *BatchStats) GetMinRating() float64 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *BatchStats) GetTotalRuntime() int32 {
	if x != nil {
		return x.TotalRuntime
	}
	return 0
}

var File_proto_examples_batch_batch_proto protoreflect.FileDescriptor

const file_proto_examples_batch_batch_proto_rawDesc = "" +
	"\n" +
	" proto/examples/batch/batch.proto\x12\x15docket.examples.batch\"\x98\x01\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12'\n" +
	"\x0fruntime_minutes\x18\x04 \x01(\x05R\x0eruntimeMinutes\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x12\x14\n" +
	"\x05genre\x18\x06 \x01(\tR\x05genre\"\xdc\x01\n" +
	"\rEnrichedMovie\x128\n" +
	"\boriginal\x18\x01 \x01(\v2\x1c.docket.examples.batch.MovieR\boriginal\x120\n" +
	"\x14above_average_rating\x18\x02 \x01(\bR\x12aboveAverageRating\x122\n" +
	"\x15above_average_runtime\x18\x03 \x01(\bR\x13aboveAverageRuntime\x12+\n" +
	"\x11rating_percentile\x18\x04 \x01(\x01R\x10ratingPercentile\"\xd5\x01\n" +
	"\n" +
	"BatchStats\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12'\n" +
	"\x0faverage_runtime\x18\x03 \x01(\x01R\x0eaverageRuntime\x12\x1d\n" +
	"\n" +
	"max_rating\x18\x04 \x01(\x01R\tmaxRating\x12\x1d\n" +
	"\n" +
	"min_rating\x18\x05 \x01(\x01R\tminRating\x12#\n" +
	"\rtotal_runtime\x18\x06 \x01(\x05R\ftotalRuntimeB\x1dZ\x1bdocket/proto/examples/batchb\x06proto3"

var (
	file_proto_examples_batch_batch_proto_rawDescOnce sync.Once
	file_proto_examples_batch_batch_proto_rawDescData []byte
)

func file_proto_examples_batch_batch_proto_rawDescGZIP() []byte {
	file_proto_examples_batch_batch_proto_rawDescOnce.Do(func() {
		file_proto_examples_batch_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_examples_batch_batch_proto_rawDesc), len(file_proto_examples_batch_batch_proto_rawDesc)))
	})
	return file_proto_examples_batch_batch_proto_rawDescData
}

var file_proto_examples_batch_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_examples_batch_batch_proto_goTypes = []any{
	(*Movie)(nil),         // 0: docket.examples.batch.Movie
	(*EnrichedMovie)(nil), // 1: docket.examples.batch.EnrichedMovie
	(*BatchStats)(nil),    // 2: docket.examples.batch.BatchStats
}
var file_proto_examples_batch_batch_proto_depIdxs = []int32{
	0, // 0: docket.examples.batch.EnrichedMovie.original:type_name -> docket.examples.batch.Movie
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_examples_batch_batch_proto_init() }
func file_proto_examples_batch_batch_proto_init() {
	if File_proto_examples_batch_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_examples_batch_batch_proto_rawDesc), len(file_proto_examples_batch_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_examples_batch_batch_proto_goTypes,
		DependencyIndexes: file_proto_examples_batch_batch_proto_depIdxs,
		MessageInfos:      file_proto_examples_batch_batch_proto_msgTypes,
	}.Build()
	File_proto_examples_batch_batch_proto = out.File
	file_proto_examples_batch_batch_proto_goTypes = nil
	file_proto_examples_batch_batch_proto_depIdxs = nil
}
